INSERT INTO silver.erp_CUST_AZ12(CID,BDATE,GEN)
SELECT
CASE WHEN CID LIKE 'NAS%' then SUBSTRING(CID,4,LEN(CID))
	 ELSE CID 
END CID,
CONVERT(DATE,BDATE,103) AS BDATE,
CASE WHEN TRIM(GEN) IN ('F','Female') THEN 'Female'
	 WHEN TRIM(GEN) IN ('M','Male') THEN 'Male'
	 ELSE 'n/a'
END GEN
FROM bronze.erp_CUST_AZ12
