INSERT INTO silver.erp_LOC_A101(
CID,
CNTRY
)
SELECT 
TRIM(REPLACE(CID,'-','')) AS CID, 
CASE WHEN TRIM(CNTRY) = 'DE' THEN 'Germany'
	 WHEN TRIM(CNTRY) IN ('US','USA') THEN 'United States'
	 WHEN TRIM(CNTRY) IS NULL or TRIM(CNTRY)='' THEN 'n/a'
	 ELSE TRIM(CNTRY)
END CNTRY
FROM bronze.erp_LOC_A101
